id = "bruno"
name = "Bruno"
version = "0.1.0"
schema_version = 1
authors = ["Wouter Leistra"]
description = "Bruno (.bru) language support for Zed"
repository = "https://github.com/freska-fi/zed-bruno"

[grammars.bruno]
repository = "https://github.com/Scalamando/tree-sitter-bruno"
rev = "dd27fe0eff8e7f8184dfc91e426b886dc8369c46"
