id = "bruno"
name = "Bruno"
version = "0.1.0"
schema_version = 1
authors = ["Wouter Leistra"]
description = "Bruno (.bru) language support for Zed"
repository = "https://github.com/freska-fi/zed-bruno"

[grammars.bruno]
repository = "https://github.com/freska-fi/tree-sitter-bruno"
rev = "82c9674c0b6c3815b90355364e990b2355f68cc1"
